name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hvac
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/hvac?pgbouncer=false

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (root)
        run: npm ci

      - name: Prisma generate
        working-directory: backend
        run: npx prisma generate

      - name: Backend tests
        working-directory: backend
        run: npm test

      - name: Generate OpenAPI
        working-directory: backend
        run: npm run openapi:gen

      - name: Generate typed API client
        working-directory: frontend
        run: npm run api:gen

      - name: Frontend typecheck
        working-directory: frontend
        run: npm run build
      - name: OpenAPI drift check
        run: |
          git status --porcelain
          git diff --name-only --exit-code backend/openapi.json frontend/src/api || (echo 'OpenAPI or client drift detected. Run backend openapi:gen and frontend api:gen and commit the results.' && exit 1)